# Generated by Django 5.1.1 on 2025-01-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='testing_field',
            field=models.CharField(default='testing', max_length=255),
        ),
    ]
