# Generated by Django 5.1.1 on 2025-01-15 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='user_hobbies', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hobby',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='hobbies',
            field=models.ManyToManyField(related_name='users_hobbies', to='api.hobby'),
        ),
    ]
