# Generated by Django 5.1.1 on 2025-01-15 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_hobby_user_alter_hobby_name_alter_myuser_hobbies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='user',
        ),
    ]
