# Generated by Django 5.1.1 on 2025-01-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_hobby_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='hobbies',
            field=models.ManyToManyField(related_name='users', to='api.hobby'),
        ),
    ]
